25 remaining errors and 9 can be fixed by unsafe fix by ruff:
blackbox\joiner.py:2:29: F401 [*] `blackbox.models.AllData` imported but unused
blackbox\joiner.py:3:18: F401 [*] `pandas` imported but unused
blackbox\joiner.py:21:5: F841 Local variable `asset` is assigned to but never used
blackbox\main.py:1:20: F401 [*] `typing.Dict` imported but unused
blackbox\main.py:6:57: F401 [*] `blackbox.cvm_runtime.response_to_get_config.GetConfigResponse` imported but unused
blackbox\main.py:9:5: F401 [*] `blackbox.models.CosmosChains` imported but unused
blackbox\main.py:10:5: F401 [*] `blackbox.models.NeutronPoolsResponse` imported but unused
blackbox\main.py:13:45: F401 [*] `blackbox.neutron_pools.Model` imported but unused
blackbox\main.py:16:50: F401 [*] `cosmpy.aerial.contract.LedgerContract` imported but unused
blackbox\main.py:18:38: F401 [*] `blackbox.cvm_runtime.query` imported but unused
blackbox\main.py:25:20: F401 [*] `typing.List` imported but unused
blackbox\main.py:27:18: F401 [*] `pandas` imported but unused
blackbox\main.py:83:5: F841 Local variable `client` is assigned to but never used
blackbox\playground.py:10:1: E402 Module level import not at top of file
blackbox\settings.py:1:22: F401 [*] `pydantic.BaseModel` imported but unused
blackbox\settings.py:2:45: F401 [*] `pydantic_settings.SettingsConfigDict` imported but unused
simulation\orders\matching.py:8:5: F401 [*] `objects.CFMMSolver` imported but unused
simulation\orders\matching.py:42:5: F841 Local variable `order_book` is assigned to but never used
simulation\orders\objects.py:5:39: F401 [*] `typing.get_type_hints` imported but unused
simulation\orders\objects.py:11:22: F401 [*] `.routers.bruno_original_solver` imported but unused
simulation\orders\objects.py:22:9: F841 Local variable `t1` is assigned to but never used
simulation\orders\objects.py:25:9: F841 Local variable `t2` is assigned to but never used
simulation\routers\bruno.py:7:1: E402 Module level import not at top of file
simulation\routers\bruno.py:40:52: E741 Ambiguous variable name: `l`
simulation\routers\bruno.py:43:53: E741 Ambiguous variable name: `l`
simulation\routers\data.py:3:23: F401 [*] `functools.cache` imported but unused
simulation\routers\data.py:10:25: F401 [*] `methodtools.lru_cache` imported but unused
simulation\routers\data.py:111:9: F811 Redefinition of unused `replace_nan_with_None` from line 87
simulation\routers\data.py:240:36: E711 Comparison to `None` should be `cond is not None`
simulation\routers\dzmitry.py:10:1: E402 Module level import not at top of file
simulation\routers\dzmitry.py:10:53: F401 [*] `simulation.routers.data.TId` imported but unused
simulation\routers\dzmitry.py:10:58: F401 [*] `simulation.routers.data.TNetworkId` imported but unused
simulation\routers\dzmitry.py:164:9: E722 Do not use bare `except`
simulation\routers\dzmitry.py:184:9: E722 Do not use bare `except`
simulation\routers\test_bruno.py:48:5: F841 Local variable `tol` is assigned to but never used
simulation\routers\test_bruno.py:120:24: F841 Local variable `l_max` is assigned to but never used
simulation\routers\test_bruno.py:120:31: F841 Local variable `p_max` is assigned to but never used
simulation\routers\test_bruno.py:122:9: E722 Do not use bare `except`
simulation\routers\test_bruno.py:136:20: E741 Ambiguous variable name: `l`
simulation\routers\test_bruno.py:149:9: E722 Do not use bare `except`
simulation\routers\test_data.py:2:23: F401 [*] `functools.cache` imported but unused
simulation\routers\test_data.py:4:18: F401 [*] `pandas` imported but unused
simulation\routers\test_data.py:5:18: F401 [*] `enum.Enum` imported but unused
simulation\routers\test_data.py:6:20: F401 [*] `typing.TypeVar` imported but unused
simulation\routers\test_data.py:6:29: F401 [*] `typing.Generic` imported but unused
simulation\routers\test_data.py:7:22: F401 [*] `pydantic.BaseModel` imported but unused
simulation\routers\test_data.py:7:33: F401 [*] `pydantic.validator` imported but unused
simulation\routers\test_data.py:8:35: F401 [*] `strictly_typed_pandas.DataSet` imported but unused
simulation\routers\test_data.py:11:5: F401 [*] `mantis.simulation.routers.data.AssetPairsXyk` imported but unused
simulation\routers\test_dzmitry.py:24:1: E402 Module level import not at top of file