blackbox\joiner.py:19:5: F841 Local variable `asset` is assigned to but never used blackbox\main.py:75:5: F841 Local variable `client` is assigned to but never used blackbox\playground.py:10:1: E402 Module level import not at top of file simulation\orders\matching.py:41:5: F841 Local variable `order_book` is assigned to but never used simulation\orders\objects.py:21:9: F841 Local variable `t1` is assigned to but never used simulation\orders\objects.py:24:9: F841 Local variable `t2` is assigned to but never used simulation\routers\bruno.py:7:1: E402 Module level import not at top of file simulation\routers\bruno.py:40:52: E741 Ambiguous variable name: `l` simulation\routers\bruno.py:43:53: E741 Ambiguous variable name: `l` simulation\routers\data.py:109:9: F811 Redefinition of unused `replace_nan_with_None` from line 85 simulation\routers\data.py:238:36: E711 Comparison to `None` should be `cond is not None` simulation\routers\dzmitry.py:10:1: E402 Module level import not at top of file simulation\routers\dzmitry.py:164:9: E722 Do not use bare `except` simulation\routers\dzmitry.py:184:9: E722 Do not use bare `except` simulation\routers\test_bruno.py:48:5: F841 Local variable `tol` is assigned to but never used simulation\routers\test_bruno.py:120:24: F841 Local variable `l_max` is assigned to but never used simulation\routers\test_bruno.py:120:31: F841 Local variable `p_max` is assigned to but never used simulation\routers\test_bruno.py:122:9: E722 Do not use bare `except` simulation\routers\test_bruno.py:136:20: E741 Ambiguous variable name: `l` simulation\routers\test_bruno.py:149:9: E722 Do not use bare `except` simulation\routers\test_dzmitry.py:6:1: E402 Module level import not at top of file simulation\routers\test_dzmitry.py:21:1: E402 Module level import not at top of file simulation\routers\test_dzmitry.py:22:1: E402 Module level import not at top of file simulation\routers\test_dzmitry.py:22:17: F811 Redefinition of unused `np` from line 2 simulation\routers\test_dzmitry.py:24:1: E402 Module level import not at top of file